# SPDX-License-Identifier: MIT
---
dist: bionic
language: python
env:
  global:
    - LSR_ANSIBLES='ansible==2.7.* ansible==2.8.* ansible==2.9.*'
    - LSR_MSCENARIOS='default'
matrix:
  include:
    - python: 2.6
      dist: trusty
      arch: amd64
    - python: 2.7
      arch: amd64
    - python: 3.6
      arch: amd64
    - python: 3.7
      arch: amd64
    - python: 3.8
      arch: amd64
    - python: 3.8-dev
      arch: amd64
    - python: 2.6
      dist: trusty
      arch: ppc64le
    - python: 2.7
      arch: ppc64le
    - python: 3.6
      arch: ppc64le
    - python: 3.7
      arch: ppc64le
    - python: 3.8
      arch: ppc64le
    - python: 3.8-dev
      arch: ppc64le

services:
  - docker

before_install:
  - ./.travis/preinstall

install:
  - pip install tox tox-travis

script:
  - ./.travis/runtox
